---
title: "Analysis"
author: "Austin Martinez"
format: html
editor: visual
---

# Background

```{r}
# If you don't have these packages installed(dplyr, tidyverse, slider, here) downloaded use the install.packages.R script in scripts/supporting code
```

```{r}
# This read in my function for library function
source(here::here("scripts", "R", "library_function.R"))

# This loaded in all 4 packages
load_library(c("dplyr", "tidyverse", "slider", "here"))

```

# Data

```{r}
# Reading in CSVs
# I cleaned the Data on a seperate R script called clean_code.qmd in Scripts/Supporting Code
q1_unique <-read_csv(here::here("outputs", "cleaned_data", "q1_unique.csv"))
q2_unique <- read_csv(here::here("outputs", "cleaned_data", "q2_unique.csv"))
q3_unique <- read_csv(here::here("outputs", "cleaned_data", "q3_unique.csv"))
prm_unique <- read_csv(here::here("outputs", "cleaned_data", "prm_unique.csv"))


```

# Methods

```{r}
# Calculation centered moving average for NH4_N, Ca, Mg, NO3_N, and K for each data with a 9 week sliding window.
# Calculation moving average for Q1
q1collumns <- c("nh4_n", "ca", "mg", "no3_n", "k")
for (col in q1collumns) {
  # Creates a new column with the name [contaminit] + _rolling_avg
  q1_unique <- q1_unique %>% # Won't work with |> pipes. 
    mutate(
      !!paste0(col, "_rolling_avg") := slide_index_dbl( 
        .x = .[[col]], # Columns being iterated over and what mean is being applied too
        .i = sample_date, # Dates are used to determine the rolling avg window 
        .f = ~mean(.x, na.rm = TRUE), # This is the function used and ignores the NAs
        # .before/.after make the window be 9 weeks
        .before = (7*9)/2,   
        .after  = (7*9)/2,
        .complete = FALSE # This allows incomplete windows at the start and end of dates column
      )
    )
}

# Calculation moving average for Q2
q2collumns <- c("nh4_n", "ca", "mg", "no3_n", "k")
for (col in q2collumns) {
  q2_unique <- q2_unique %>%
    mutate(
      !!paste0(col, "_rolling_avg") := slide_index_dbl(
        .x = .[[col]],
        .i = sample_date,
        .f = ~mean(.x, na.rm = TRUE),  
        .before = (7*9)/2,
        .after  = (7*9)/2,
        .complete = FALSE
      )
    )
}

# Calculation moving average for Q3
q3collumns <- c("nh4_n", "ca", "mg", "no3_n", "k")
for (col in q3collumns) {
  q3_unique <- q3_unique %>%
    mutate(
      !!paste0(col, "_rolling_avg") := slide_index_dbl(
        .x = .[[col]],
        .i = sample_date,
        .f = ~mean(.x, na.rm = TRUE),  
        .before = (7*9)/2, 
        .after  = (7*9)/2,
        .complete = FALSE
      )
    )
}

# Calculation moving average for Q3
prmcollumns <- c("nh4_n", "ca", "mg", "no3_n", "k")
for (col in prmcollumns) {
  prm_unique <- prm_unique %>%
    mutate(
      !!paste0(col, "_rolling_avg") := slide_index_dbl(
        .x = .[[col]],
        .i = sample_date,
        .f = ~mean(.x, na.rm = TRUE),
        .before = (7*9)/2,
        .after  = (7*9)/2,
        .complete = FALSE
      )
    )
}

# Combing all data sets(q1_unique, q2_unique, q3_unique, prm_unique) into one.
river_df <- bind_rows(q1_unique, q2_unique, q3_unique, prm_unique)

# Pivoting longer so I can facet wrap my ggplot for contaminants
river_long <- pivot_longer(data = river_df, 
                           cols =  c("nh4_n_rolling_avg", "ca_rolling_avg", 
                                     "mg_rolling_avg", "no3_n_rolling_avg",
                                     "k_rolling_avg"), 
                           names_to = "contaminant", 
                           # Putting column names into contaminant column
                           values_to = "rolling_avgs") 
                           # Putting column values into rolling_avgs column
```

# Results

```{r}
# Generates ggplot

# This read in my function for ggplot theme
source(here::here("scripts", "R", "awesome_function.R"))

# Specifies the hurricane date for geom_vline
hurricane_date <- ymd("1989-09-18")

# Ignores the NAs in rolling_avgs and generates a ggplot
Rolling_mean_plot <- ggplot(data = river_long %>% 
         filter(!is.na(rolling_avgs)), #ignores NAs
  aes(x = sample_date, y = rolling_avgs, color = sample_id)) + # Sets my sample_date as x and rolling_avgs as y
  geom_line() + 
  Schaefer_theme() # Adds the theme I made

Rolling_mean_plot
```

```{r}
# Saving my ggplot to the outputs folder
ggsave(Rolling_mean_plot, file = here("outputs", "Rolling_mean_plot.png"))
```


